# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "btrfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=nixos/root" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=nixos/nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=nixos/home" "compress=zstd" ];
    };

  fileSystems."/home/nerd/Downloads" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=downloads" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/nerd/.ssh" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=ssh" "compress=zstd" ];
    };

  fileSystems."/home/nerd/workspaces" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=workspaces" "compress=zstd" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/c65218c8-cb4e-492e-bac4-eb1efc953c31";
      fsType = "btrfs";
      options = [ "subvol=swap" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
